[DEFAULT]

[Preprocess]
input_dir = ../../synergy_v2
output_dir = ./testing_preprocess
train_split_file = ['ONEIL_split_1_train.txt']
val_split_file = ['ONEIL_split_1_val.txt']
test_split_file = ['ONEIL_split_1_test.txt']
data_format = .npy
embeddings_dir = results_mgaedc_representation
y_col_name = loewe
cell_transcriptomic_file = cell_transcriptomics.tsv
drug_infomax_file = drug_infomax.tsv

#TODO
[Train]
input_dir = ./testing_preprocess
output_dir = ./testing_train
model_file_format = .pt
learning_rate = 0.0005
#epochs = 1000
epochs = 2
batch_size = 256
val_batch = 256
patience = 100
data_format = .pkl
y_col_name = loewe
metric_type = classification

[Infer]
y_col_name = loewe
model_file_format = .pt
infer_batch = 256
calc_infer_scores = True
input_data_dir = ./testing_preprocess
input_model_dir = ./testing_train
output_dir = ./testing_infer
metric_type = classification